// <auto-generated />
using System;
using Gateway.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gateway.Infrastructure.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gateway.Domain.Events.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("OrderRef");

                    b.HasIndex("StoreId");

                    b.ToTable("OrderEvents", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Orders.CanonicalOrder", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InternalId"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CancelReason")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<long>("DeliveryFeeCents")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FulfillmentType")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("PlacedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PosOrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Prepaid")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ScheduledForUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SubtotalCents")
                        .HasColumnType("bigint");

                    b.Property<long>("TaxCents")
                        .HasColumnType("bigint");

                    b.Property<long>("TipCents")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalCents")
                        .HasColumnType("bigint");

                    b.HasKey("InternalId");

                    b.HasIndex("OrderRef")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchedAtUtc");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Tenancy.BillingRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<long>("RateCents")
                        .HasColumnType("bigint");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "EffectiveFrom");

                    b.ToTable("BillingRates", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Tenancy.ChannelConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChannelType")
                        .HasColumnType("int");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("LocationKeyRotatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreviousLocationKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SigningSecretRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationKey")
                        .IsUnique();

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.ToTable("ChannelConnections", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Tenancy.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Tenancy.PosConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalLocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalNodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraConfig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosType")
                        .HasColumnType("int");

                    b.Property<string>("SecretRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.ToTable("PosConnections", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Tenancy.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("StateChangeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StateChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("Gateway.Domain.Orders.CanonicalOrder", b =>
                {
                    b.OwnsMany("Gateway.Domain.Orders.CanonicalOrderItem", "Items", b1 =>
                        {
                            b1.Property<long>("CanonicalOrderInternalId")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<string>("ExternalProductId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Notes")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.Property<long>("TotalPriceCents")
                                .HasColumnType("bigint");

                            b1.Property<long>("UnitPriceCents")
                                .HasColumnType("bigint");

                            b1.HasKey("CanonicalOrderInternalId", "Id");

                            b1.ToTable("Orders");

                            b1.ToJson("Items");

                            b1.WithOwner()
                                .HasForeignKey("CanonicalOrderInternalId");

                            b1.OwnsMany("Gateway.Domain.Orders.CanonicalModifier", "Modifiers", b2 =>
                                {
                                    b2.Property<long>("CanonicalOrderItemCanonicalOrderInternalId")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("CanonicalOrderItemId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<string>("ExternalModifierId")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("GroupExternalId")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<long>("PriceDeltaCents")
                                        .HasColumnType("bigint");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int");

                                    b2.HasKey("CanonicalOrderItemCanonicalOrderInternalId", "CanonicalOrderItemId", "Id");

                                    b2.ToTable("Orders");

                                    b2.WithOwner()
                                        .HasForeignKey("CanonicalOrderItemCanonicalOrderInternalId", "CanonicalOrderItemId");
                                });

                            b1.Navigation("Modifiers");
                        });

                    b.OwnsOne("Gateway.Domain.Orders.CustomerInfo", "Customer", b1 =>
                        {
                            b1.Property<long>("CanonicalOrderInternalId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CanonicalOrderInternalId");

                            b1.ToTable("Orders");

                            b1.ToJson("Customer");

                            b1.WithOwner()
                                .HasForeignKey("CanonicalOrderInternalId");
                        });

                    b.OwnsOne("Gateway.Domain.Orders.DeliveryAddress", "DeliveryAddress", b1 =>
                        {
                            b1.Property<long>("CanonicalOrderInternalId")
                                .HasColumnType("bigint");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("float");

                            b1.Property<string>("Line1")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("float");

                            b1.Property<string>("Notes")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CanonicalOrderInternalId");

                            b1.ToTable("Orders");

                            b1.ToJson("DeliveryAddress");

                            b1.WithOwner()
                                .HasForeignKey("CanonicalOrderInternalId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
